version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Build phase – no npm install"

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - node_modules/**   # 🔥 THIS IS THE KEY
