version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies"
      - npm install

  build:
    commands:
      - echo "Build phase (no build needed for Node app)"

artifacts:
  files:
    - appspec.yml
    - index.js
    - package.json
    - package-lock.json
    - public/**/*
    - scripts/**/*
